### ISSUE TITLE
Грешновато

### ISSUE THREAD

**Issue by in-in** [yoksel/common-words#18]
![1](https://cloud.githubusercontent.com/assets/8797432/16098456/bd963208-335b-11e6-9e93-e928c75f95ce.png)

Пример свёрстан не по БЭМу, в отличие от других примеров. Если проповедники методологии заметят, возможны гонения. Предлагаю изменить. 
Аминь

**Comment by jt3k** [comment]
блоки внутри других блоков норм - по бему.  
Другое дело что люди начинающие разбираться в беме  могут взять этот пример за правило, и не юзить элементы внутри списков.

С другой стороны если испозьзовать по-привычному, то этот пример станет громоздким.

```html
<ul class="list">
	<li class="list__item"><span class="list-item">Lorem.</span></li>
	<li class="list__item"><span class="list-item">Blanditiis.</span></li>
	<li class="list__item"><span class="list-item">Temporibus.</span></li>
	<li class="list__item"><span class="list-item">Saepe.</span></li>
	<li class="list__item"><span class="list-item">Voluptates.</span></li>
</ul>

<ul class="list">
	<li class="list__item list-item">Lorem.</li>
	<li class="list__item list-item">Nulla!</li>
	<li class="list__item list-item">Repudiandae.</li>
	<li class="list__item list-item">Consequatur?</li>
	<li class="list__item list-item">Aliquid.</li>
</ul>
```

**Comment by yoksel** [comment]
В контексте конкретного блока всё будет нормально:

```html
<div class="features">
    <ul class="features__list">
        <li class="features__item">Первое</li>
        <li class="features__item">Второе</li>
        <li class="features__item">Третье</li>
    </ul>
</div>
```

Подразумевается, что `.item` — это перечисляемый элемент внутри `.list`, поэтому указание вложенности можно опустить, тем более, что важнее будет принадлежность к родительскому блоку, а не к списку.

**Comment by in-in** [comment]
@yoksel Мне это понятно и очевидно.

>Если собрать такие слова в одном месте, получится хороший справочник для начинающих верстальщиков

Для начинающих может быть не так очевидно. Возможно я плохого мнения о них).
Некоторые новички ассоциируют html дерево с бэм деверевом. И пишут элемент элемента `features__list__item`

Но я не настаиваю. Пусть будет как есть весьма лаконично.

**Comment by yoksel** [comment]
@in-in пример как раз показывает, что в `.item` не нужно указывать вложенность в `.list`. Да и в момент создания элемента элемента у них наверняка возникнет ощущение, что что-то пошло не так : )
