### ISSUE TITLE
add group or/and divider

### ISSUE THREAD

**Issue by Varenkov** [yoksel/common-words#33]
group – если что-то нужно сгруппировать по смыслу

прим.:
```pug
ul.menu
	div.menu__group
		li.menu__list-item
			a.menu__item(href="#0") Dashboard
	div.menu__group
		li.menu__list-item
			a.menu__item(href="#0") Account
		li.menu__list-item
			a.menu__item(href="#0") Settings
	div.menu__group
		li.menu__list-item
			a.menu__item(href="#0") Log out
```

divider – если что-то нужно разделить

прим.:
```pug
ul.menu
	li.menu__list-item
		a.menu__item(href="#0") Dashboard
	hr.divider
	li.menu__list-item
		a.menu__item(href="#0") Account
	li.menu__list-item
		a.menu__item(href="#0") Settings
	hr.divider
	li.menu__list-item
		a.menu__item(href="#0") Log out
```

**Comment by yoksel** [comment]
Меня несколько смущают примеры. Во-первых, они не пройдут валидатор из-за недопустимых тегов, во-вторых, не вполне понятно зачем в данном случае делать разделитель отдельным тегом, а не стилями

**Comment by Varenkov** [comment]
Ок, над примерами я еще подумаю. Есть ли еще какие-то сомнения?

**Comment by yoksel** [comment]
В целом идея выглядит логичной, и класс `divider` мог бы действительно пригодится для `hr`, только не в таком контексте (см. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)). А вот к `group` есть вопросы: если группируются однородные элементы, почему бы не поместить их в список? Хотелось бы пример, когда все остальные варианты контейнеров из словаря не подходят

**Comment by Varenkov** [comment]
Как насчет таких примеров для `.divider`

1. Как отдельный элемент
```pug
.menu
	a.menu__item(href="#0") Dashboard
	hr.divider
	a.menu__item(href="#0") Account
	a.menu__item(href="#0") Settings
	hr.divider
	a.menu__item(href="#0") Log out
```

2. Как микс:
```pug
ul.menu
	li.menu__list-item.divider
		a.menu__item(href="#0") Dashboard
	li.menu__list-item
		a.menu__item(href="#0") Account
	li.menu__list-item.divider
		a.menu__item(href="#0") Settings
	li.menu__list-item
		a.menu__item(href="#0") Log out
```

По поводу `.group` сходу приходят в голову только формы

**Comment by jt3k** [comment]
примеры c ul > li из первого поста не корректные, т.к. внутри ul [не разрешено](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul) ничего кроме li, script и template элементов
