### ISSUE TITLE
Add 'snippet' to text

### ISSUE THREAD

**Issue by skirienko** [yoksel/common-words#35]
## Текст
`snippet` — вырезка, небольшой фрагмент текста или кода

(кто-то считает это синонимом не для `excerpt`, а для `widget`, так что можно и в Блоки)

**Comment by yoksel** [comment]
По-моему, это всё-таки относится к тексту, а не к блокам : ) И скорее всего, это будет код, потому что для врезок обычного текста есть другие подходящие теги и классы

**Comment by yoksel** [comment]
Добавила
