### ISSUE TITLE
common words

### ISSUE THREAD

**Issue by agentfreedom** [yoksel/common-words#44]
Слова часто используемые для названия css классов

**Comment by jt3k** [comment]
Вы предлагаете переименоватьэтот список ?

**Comment by agentfreedom** [comment]
Ні!

Я хотів зберегти для себе, а плюсик у кружочку в мобільній версії githab,
надихнув мене на це збереження)))

Вибачаюсь, якщо щось зломав!!!

Дякую!

пн, 18 янв. 2021 г., 11:05 Andrey Gurtovoy <notifications@github.com>:
