### ISSUE TITLE
menu?

### ISSUE THREAD

**Issue by igoradamenko** [yoksel/common-words#9]
Могу ошибаться, но всё же тег `menu` не используется в том смысле, в каком он описан в последнем примере. [В спеке](https://www.w3.org/TR/html51/interactive-elements.html#the-menu-element) примеры описывают построение интерфейсных меню. 

Думаю, в примере должен быть `div`. PR не создаю, т. к. может быть чего-то не знаю :)

_P. S.: Вчитался в текст примеров. Он прекрасен!_

**Comment by jt3k** [comment]
Я смотрю здесь http://html5doctor.com/element-index/#menu , и кажыцо всо ок.   
Надо читать "if the element has no li element children, flow content describing available commands."

**Comment by igoradamenko** [comment]
Во-первых, `menu` в спеке находится в разделе интерактивных элементов, что, наверное, намекает на то, что элемент будет как-то обрабатываться браузером. Рядом с ним там `details`/`summary`, так что можно примерно прикинуть, как.

Во-вторых, `menu` определяет список «команд». Команда — это абстракция, которая меняет состояние. У неё может быть label, access key и пр.

В-третьих, чаще всего у этого тега есть атрибут `type`, возможные значения которого: `context` и `popup`, что тоже не совсем похоже на то, что в примере.

В-четвёртых, есть довольно-таки [популярный вопрос на СО](https://stackoverflow.com/questions/4969801/nav-or-menu-html5), где англоязычные ребята трактуют написанное в спеке. В целом они сходятся к тому, что `toolbar` и `context` — это не просто так, и в общем-то этот тег для веб-приложений, а не веб-страниц. Тут конечно можно развести дискуссию о том, что такое веб-приложение, но предлагаю считать в этом контексте веб-приложением то, у чего есть контекстное меню. Сейчас на моей памяти ничего, кроме Slack мне в голову не приходит. Т. е. реально *приложение*.

Даже если мы не сойдёмся в этой дискуссии на том, для чего же нужен этот тег, считаю, что из примера его стоит убрать, т. к. только путает. Примеры для новичков, а потому если они заметят тег `menu` в подобном контексте то будут пихать в него меню сайтов и пр., для чего явно есть другие теги (тот же `nav`, например).

**Comment by yoksel** [comment]
@igoradamenko вы правы, я слишком вольно распрядилась тегом. Поправила примеры.
